# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaNIpmQTkLnO7dz5TADscza9t1Ksxz7b
"""



import cv2
import matplotlib.pyplot as plt
import numpy as np

pip install opencv-python matplotlib

import matplotlib.pyplot as plt

image = cv2.imread('rasm1.jpg')
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title('Original Rasm')
plt.axis('off')

colors = ['r', 'g', 'b']
plt.subplot(1, 2, 2)
for i, color in enumerate(colors):
    histogram = cv2.calcHist([image], [i], None, [256], [0, 256])
    plt.plot(histogram, color=color)
    plt.xlim([0, 256])

plt.title('Histogram')
plt.xlabel('Rang darajalari')
plt.ylabel('Piksellar soni')

plt.tight_layout()
plt.show()